 .travis.yml                                                                                                                                    
 launguage: cpp
 dist: trusty
 sudo: require
 os: linux
 compiler: gcc
 
 os:
   - linux
 
 compiler:
   - g++
   - clang
 
 script:
     - mkdir build
     - cd build
     - cmake ..
     - make
     - ./StudentDatabase