version: 2.0
jobs:
    build:
        docker:
        - image: gcc:6
        steps:
        - checkout
        - run:
            curl -sSL https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz | sudo tar -xzC~
            cmake ..
            make
